### PR TITLE
Add timeout utility function

### LINKED ISSUE #111: add `timeout` utility

### PR DESCRIPTION
**Pull request by nickschot**
This PR adds the `timeout` utility function. It also updates all the tests, example code and examples to use it.

Closes #111

### CODE REVIEW

**Comment by beerinho** [comment]
What do you think about testing the timeout? Both options seem a bit strange, but thankfully Vitest has time faking built in - https://vitest.dev/api/vi.html#fake-timers - so hopefully it'd be quite straightforward

**Comment by nickschot** [comment]
> What do you think about testing the timeout? Both options seem a bit strange, but thankfully Vitest has time faking built in - https://vitest.dev/api/vi.html#fake-timers - so hopefully it'd be quite straightforward

Yeah so currently it's indirectly tested through all other tests. Testing it directly should be possible (without fake timers) though. I'll add something.

**Comment by nickschot** [comment]
> What do you think about testing the timeout? Both options seem a bit strange, but thankfully Vitest has time faking built in - https://vitest.dev/api/vi.html#fake-timers - so hopefully it'd be quite straightforward

Added some tests, 1 without fake timers (since I wanted to verify the microtick) and 1 with fake timers (to check the longer duration).

**Review by paoloricciuti — APPROVED** [review]
Very cool...i'm wondering if we should expose utils as an export instead of "polluting" the main export. We could also export `didCancel` from there.

WDYT? Feel free to merge if you think it should be from the main one or refactor and merge otherwise! 🚀

**Comment by nickschot** [comment]
> Very cool...i'm wondering if we should expose utils as an export instead of "polluting" the main export. We could also export `didCancel` from there.
> 
> WDYT? Feel free to merge if you think it should be from the main one or refactor and merge otherwise! 🚀

We didn't seem to have a very clear strategy about that yet, let's discuss during the sync.

**Pull request merged**
