### PR TITLE
fix: monorepo settings

### PR DESCRIPTION
**Pull request by paoloricciuti**
Some file to move around

### CODE REVIEW

**Review by beerinho — APPROVED** [review]
Do we really want to have the changelog at the root instead of within the packages folder? If you think so then let's go for it

Also, I know I added it but please can you make sure everything in the tsconfig makes sense to you

**Comment by paoloricciuti** [comment]
> Do we really want to have the changelog at the root instead of within the packages folder? If you think so then let's go for it
> 
> Also, I know I added it but please can you make sure everything in the tsconfig makes sense to you

I think @nickschot said it has to be in the root for the moment...we might be able to change it later or maybe prepare release itself will change it

**Comment by paoloricciuti** [comment]
Also yeah i'll check the `tsconfig`

**Comment by paoloricciuti** [comment]
I moved the moduleResolution to bundler...i'm not entirely sure about that but given that we will always bundle our packages/apps i think it shouldn't create problems and it's better than node (if we don't want bundler we should probably go with NodeNext)

**Pull request merged**
